In [68]:
import os
import sys
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError
import matplotlib.pyplot as plt
import csv

In [69]:
SharkData = pd.read_csv('https://raw.githubusercontent.com/cphyland/Project-2/main/data/sharks/shark_sightings_raw.csv',index_col=False)
SharkData.head()
df = SharkData
df.head()

,Unnamed: 0,RawDataId,ObjectId,Distance,DistanceUnit,InteractionValue,InteractionId,TownProximity,LocationValue,SightingNumbervalue,ReportDateTime,SightingDateTime,SightingSizeValue,SightingSpeciesValue,OwnerValue,LocationDetail,LocationX,LocationY
0,0,63739,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:48:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
1,1,63738,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:43:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
2,2,63737,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:38:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
3,3,63736,WA12582TSE,50.0,m offshore,sighted,1,Perth Metro,"Jervoise Bay Beach, Perth Metro",NaN,NaN,2021-07-24T12:15:12,2.5m,unknown sp.,Public report,NaN,115.765000,-32.13930
4,4,63735,WA51495TSE,600.0,m offshore,sighted,1,Coral Bay,"Bateman Bay, near Coral Bay",NaN,NaN,2021-07-24T11:24:29,NaN,whale carcass,Fisheries advise,Lots of sharks around carcass,113.807000,-23.05480

In [70]:
df = df[(df['SightingDateTime'] > '2020-01-01T02:03:00') & (df['SightingDateTime'] <= '2021-07-24T17:48:00')]

In [71]:
df.head()

,Unnamed: 0,RawDataId,ObjectId,Distance,DistanceUnit,InteractionValue,InteractionId,TownProximity,LocationValue,SightingNumbervalue,ReportDateTime,SightingDateTime,SightingSizeValue,SightingSpeciesValue,OwnerValue,LocationDetail,LocationX,LocationY
0,0,63739,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:48:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
1,1,63738,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:43:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
2,2,63737,3073,NaN,NaN,Detected,4,NaN,Meelup,NaN,NaN,2021-07-24T17:38:00,NaN,white,Fisheries Advise,NaN,115.093091,-33.57247
3,3,63736,WA12582TSE,50.0,m offshore,sighted,1,Perth Metro,"Jervoise Bay Beach, Perth Metro",NaN,NaN,2021-07-24T12:15:12,2.5m,unknown sp.,Public report,NaN,115.765000,-32.13930
4,4,63735,WA51495TSE,600.0,m offshore,sighted,1,Coral Bay,"Bateman Bay, near Coral Bay",NaN,NaN,2021-07-24T11:24:29,NaN,whale carcass,Fisheries advise,Lots of sharks around carcass,113.807000,-23.05480

In [72]:
df.to_csv("clean_shark_data.csv")